export const metadata = {
  title: 'MyPage',
  description: 'Generated by create next app',
};

export default function MypageLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <nav>MyPage NavBar</nav>
      {children}
    </>
  );
}
