import '@styles/global.css';

import Footer from '@components/ui/footer';
import GlobalNav from '@components/ui/global-nav';

export const metadata = {
  title: 'Next13 TypeScript Template',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body>
        <GlobalNav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
